### ISSUE TITLE
Fix moon/debris field tooltips

### ISSUE THREAD

**Issue by PhrozenByte** [skartoffel/material_blue_grey#2]
A moon and debris field can be found at 1:1:2

![bildschirmfoto von 2016-06-08 20 04 53](https://cloud.githubusercontent.com/assets/920356/15906192/1ffe17c0-2db8-11e6-8c3f-b95093d60243.png)
![bildschirmfoto von 2016-06-08 20 05 07](https://cloud.githubusercontent.com/assets/920356/15906193/1ffff450-2db8-11e6-9eec-b12cb37c5295.png)

**Comment by skartoffel** [comment]
In what way should they be fixed? Make the images visible? Change some colors? Make them have less empty space?

**Comment by PhrozenByte** [comment]
They just look a bit broken :wink:

I suggest to make both tooltips use all of the available space, action buttons (Espionage, Transport, Attack, Destroy, Harvest) should be distinguishable from regular text, the moon tooltip currently doesn't use the usual table formatting (i.e. add horizontal separation lines) and centered text makes the whole tooltip look misaligned.

**Comment by skartoffel** [comment]
The underlying HTML is awful and makes it very complicated to style all three tooltip types (moon, debris, player) very.. challenging.

<img width="186" alt="bildschirmfoto 2016-06-10 um 20 36 24" src="https://cloud.githubusercontent.com/assets/19807278/15974872/07276b72-2f4b-11e6-97d1-8f47cdcc87ad.png">

<img width="176" alt="bildschirmfoto 2016-06-10 um 20 36 50" src="https://cloud.githubusercontent.com/assets/19807278/15974875/09da2f80-2f4b-11e6-8e36-e4ffbd3613de.png">

<img width="169" alt="bildschirmfoto 2016-06-10 um 20 37 04" src="https://cloud.githubusercontent.com/assets/19807278/15974878/0b584392-2f4b-11e6-934d-d538c3bd9dcf.png">

This is what I tried so far, but I am open for new suggestions.
