### ISSUE TITLE
Add a generic planet image

### ISSUE THREAD

**Issue by PhrozenByte** [skartoffel/material_blue_grey#5]
Planet images are used for navigation (i.e. on the overview page to change the selected planet) or as shortcut to various actions (i.e. attack/transport of the planet tooltip on the galaxy page). However, the skin currently hides all planet images. A very simple, generic planet image (like the moon or DF image) should be sufficient to have "something" to click on. Otherwise e.g. the planet tooltip (galaxy page) wouldn't be usable (requires #4):

![bildschirmfoto von 2016-06-11 02 19 15](https://cloud.githubusercontent.com/assets/920356/15981824/64c3b80a-2f7b-11e6-82d3-56cc31c50f49.png)

**Comment by skartoffel** [comment]
I added the planet image (small only) to the galaxy view and the overview. The functionality should be recovered, now I am looking forward to the improved tooltips 👍
